name: cinemapedia
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  animate_do: ^3.0.2
  card_swiper: ^3.0.1
  dio: ^5.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^2.2.0
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^11.1.4
  intl: ^0.18.0
  isar: ^3.0.5
  isar_flutter_libs: ^3.0.5
  path_provider: ^2.1.1

dev_dependencies:
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  isar_generator: ^3.0.5

flutter:
  uses-material-design: true

  assets:
    - .env
