name: cinemapedia
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  animate_do: ^3.0.2
  card_swiper: ^2.0.4
  dio: ^5.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_riverpod: ^2.2.0
  go_router: ^6.0.9
  intl: ^0.18.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - .env
